name = "Juliafmt"
uuid = "5327a835-ab8c-415d-915c-7c28c77b870b"
authors = ["yanbofang2 <yf37@rice.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
