name: Format suggestions
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repo with write permissions
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # 2. Setup Julia
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1

      # 3. Install & run the formatter
      - run: |
          julia -e 'using Pkg; Pkg.add("JuliaFormatter")'
          julia -e 'using JuliaFormatter; format("."; verbose=true)'

      # ─── New steps start here ───

      # 4. Configure Git user (so commits have an author)
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 5. Commit any formatting fixes (no-op if nothing changed)
      - name: Commit formatting fixes
        run: |
          git add .
          git commit -m "chore: apply JuliaFormatter fixes" || echo "No formatting changes to commit"

      # 6. Push back to the same branch
      - name: Push changes
        run: git push origin HEAD:${{ github.ref_name }}

      # ─── New steps end here ───

      # 7. (Optional) reviewdog suggestions—in PRs this will still annotate diffs
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: JuliaFormatter
          fail_on_error: true
          filter_mode: added

        