name: Format suggestions
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repo with write permissions
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # 2. Setup Julia
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1

      # 3. Install & run the formatter
      - name: Run JuliaFormatter
        run: |
          julia -e 'using Pkg; Pkg.add("JuliaFormatter")'
          julia -e 'using JuliaFormatter; format("."; verbose=true)'

      # — Solution B: check then commit/push —

      - name: Check for formatting changes
        id: changes
        run: |
          # Refresh index for git-diff-index approach
          git update-index --really-refresh
          if git diff-index --quiet HEAD; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true"  >> $GITHUB_OUTPUT
          fi

      - name: Commit & push formatting fixes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: apply JuliaFormatter fixes"
          git push origin HEAD:${{ github.ref_name }}

      # Optional reviewdog step…
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: JuliaFormatter
          fail_on_error: true
          filter_mode: added

        